# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-05-24 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('rma', 'RMA'), ('production', 'PRODUCTION'), ('warehouse', 'WAREHOUSE'), ('maintenance', 'MAINTENANCE')], default='rma', max_length=14)),
                ('waste_type', models.CharField(choices=[('hazardous', 'HAZARDOUS'), ('e-waster', 'E-WASTE'), ('metals', 'METALS'), ('paper', 'PAPER'), ('plastic', 'PLASTIC')], default='paper', max_length=14)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
