# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-02 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0002_auto_20170524_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('additional_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.CharField(choices=[('rma', 'R.M.A.'), ('production', 'Production'), ('warehouse', 'Warehouse'), ('maintenance', 'Maintenance')], default='rma', max_length=14),
        ),
        migrations.AlterField(
            model_name='category',
            name='waste_type',
            field=models.CharField(choices=[('hazardous', 'Hazardous'), ('e-waste', 'e-Waste'), ('metals', 'Metals'), ('paper', 'Paper'), ('plastic', 'Plastic')], default='paper', max_length=14),
        ),
    ]
