# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-02 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0003_auto_20170602_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name_plural': 'Quotes'},
        ),
    ]
