# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-05 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0004_auto_20170602_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.CharField(choices=[('Smartlink Network Systems Ltd.', 'Smartlink Network Systems Ltd.'), ('Digisol Systems Ltd.', 'Digisol Systems Ltd.'), ('Synegra EMS Ltd.', 'Synegra EMS Ltd.'), ('Telesmart SCS Ltd.', 'Telesmart SCS Ltd.')], default='it', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.CharField(choices=[('hr & admin', 'HR & Admin'), ('purchase', 'Purchase'), ('rm stores', 'RM Stores'), ('synegra production', 'Synegra Production'), ('logistics & warehouse', 'Logistics & Warehouse'), ('commercial', 'Commercial'), ('accounts', 'Accounts'), ('legal', 'Legal'), ('s-tac', 'S-TAC'), ('it', 'IT'), ('qa', 'QA'), ('engineering', 'Engineering'), ('telesmart-production', 'Telesmart-Production')], default='it', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='waste_type',
            field=models.CharField(choices=[('aging material', 'Aging Material'), ('hazardous', 'Hazardous'), ('e-waste', 'E-Waste'), ('metals', 'Metals'), ('paper', 'Paper'), ('plastic', 'Plastic'), ('furniture', 'Furniture'), ('machinery', 'Machinery')], default='paper', max_length=100),
        ),
    ]
