# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-05 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0005_auto_20170605_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill', models.CharField(max_length=100)),
            ],
        ),
    ]
