# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-08 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0006_random_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.CharField(choices=[('goa', 'Goa'), ('mumbai', 'Mumbai'), ('bangalore', 'Bangalore')], default='goa', max_length=100),
        ),
        migrations.AddField(
            model_name='quote',
            name='location',
            field=models.CharField(choices=[('goa', 'Goa'), ('mumbai', 'Mumbai'), ('bangalore', 'Bangalore')], default='goa', max_length=100),
        ),
        migrations.AlterField(
            model_name='random_m',
            name='fill',
            field=models.CharField(default='aa', max_length=100),
        ),
    ]
