# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-12 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0007_auto_20170608_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time',
            field=models.CharField(default='12/06/17', max_length=20),
        ),
    ]
