# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-17 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0010_auto_20170615_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='time',
            field=models.CharField(default='17/06/17', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='time',
            field=models.CharField(default='17/06/17', max_length=20),
        ),
    ]
