# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-06-28 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0011_auto_20170617_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='trxn_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date Sold')),
                ('location', models.CharField(choices=[('goa', 'Goa'), ('mumbai', 'Mumbai'), ('bangalore', 'Bangalore')], default='goa', max_length=100)),
                ('items_description', models.CharField(max_length=10000)),
                ('purchasing_party', models.CharField(max_length=1000)),
                ('selling_price', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='time',
            field=models.CharField(default='28/06/17', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='time',
            field=models.CharField(default='28/06/17', max_length=20),
        ),
    ]
