# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-05 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0012_auto_20170628_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trxn_m',
            options={'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='category',
            name='time',
            field=models.CharField(default='05/07/17', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='time',
            field=models.CharField(default='05/07/17', max_length=20),
        ),
        migrations.AlterField(
            model_name='trxn_m',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Date Sold'),
        ),
    ]
