# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-09 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scr', '0013_auto_20170705_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='time',
            field=models.CharField(default='09/07/17', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='time',
            field=models.CharField(default='09/07/17', max_length=20),
        ),
    ]
